name: "Coalfire Technical Challenge - Manual Destroy"

on: 
    workflow_dispatch:

env:
    TF_LOG: INFO
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}


jobs:
    terraform:
        name: "Terraform Runner"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Terraform 
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.13.3

            - name: init
              id: init
              run: terraform init --backend-config="bucket=$BUCKET_TF_STATE"

            - name: Validate
              id: validate
              run: terraform validate

            - name: Plan
              id: plan
              if: github.event_name == 'pull_request'
              run: terraform plan --no-color --input=false
              continue-on-error: true

            - name: Status Check
              if: steps.plan.outcome == 'failure'
              run: exit 1

            - name: Terraform destroy
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: terraform destroy --auto-approve --input=false